In [33]:
import pandas as pd

df = pd.read_csv("sales_data.csv")
#first n records of data frame

df.head(2)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
1,ORD-10002,2025-05-07,Sony WH-1000XM5,Accessories,94182,1,EasyPaisa

In [5]:
#last n records of data frame
df.tail(2)

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
4998,ORD-14999,2025-06-25,iPhone 15,Mobile,303658,5,EasyPaisa
4999,ORD-15000,2026-03-02,Dell XPS 13,Laptop,362826,1,Cash

In [6]:
#info
df.info

<bound method DataFrame.info of        Order_ID        Date          Product     Category   Price  Quantity  \
0     ORD-10001  2025-05-14   MacBook Air M2       Laptop  396538         5
1     ORD-10002  2025-05-07  Sony WH-1000XM5  Accessories   94182         1
2     ORD-10003  2025-05-19        iPhone 15       Mobile  321269         4
3     ORD-10004  2026-01-16      Airpods Pro  Accessories   51859         5
4     ORD-10005  2025-07-02      Airpods Pro  Accessories   58606         2
...         ...         ...              ...          ...     ...       ...
4995  ORD-14996  2025-11-29        iPhone 15       Mobile  320392         4
4996  ORD-14997  2025-09-15      Airpods Pro  Accessories   54518         2
4997  ORD-14998  2025-06-06      Samsung S24       Mobile  234107         3
4998  ORD-14999  2025-06-25        iPhone 15       Mobile  303658         5
4999  ORD-15000  2026-03-02      Dell XPS 13       Laptop  362826         1

     Payment_Method
0          JazzCash
1         EasyPaisa
2          JazzCash
3       Credit Card
4       Credit Card
...             ...
4995           Cash
4996      EasyPaisa
4997       JazzCash
4998      EasyPaisa
4999           Cash

[5000 rows x 7 columns]>

In [7]:
#describe
df.describe()

               Price     Quantity
count    5000.000000  5000.000000
mean   199227.090800     2.974800
std    123078.108755     1.416674
min     10006.000000     1.000000
25%     64441.750000     2.000000
50%    231580.000000     3.000000
75%    306336.250000     4.000000
max    399904.000000     5.000000

In [9]:
#Group by counting specific column values
df["Payment_Method"].value_counts()

Payment_Method
Cash           1271
JazzCash       1261
Credit Card    1254
EasyPaisa      1214
Name: count, dtype: int64

In [22]:
#fine total records per column in data frame
df.nunique()

Order_ID          5000
Date               366
Product              8
Category             3
Price             4942
Quantity             5
Payment_Method       4
dtype: int64

In [47]:

print(df.loc[0])

Order_ID               ORD-10001
Date                  2025-05-14
Product           MacBook Air M2
Category                  Laptop
Price                     396538
Quantity                       5
Payment_Method          JazzCash
Name: 0, dtype: object

In [46]:

df.iloc[:1]

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash

In [ ]:
#querying records 
df.query('Price > 5000 and Payment_Method=="JazzCash"')

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
2,ORD-10003,2025-05-19,iPhone 15,Mobile,321269,4,JazzCash
14,ORD-10015,2026-01-04,Sony WH-1000XM5,Accessories,95576,4,JazzCash
22,ORD-10023,2025-12-24,Sony WH-1000XM5,Accessories,99482,3,JazzCash
26,ORD-10027,2026-02-21,Google Pixel 8,Mobile,240173,3,JazzCash
...,...,...,...,...,...,...,...
4982,ORD-14983,2025-06-24,iPhone 15,Mobile,308691,4,JazzCash
4987,ORD-14988,2026-02-08,Mechanical Keyboard,Accessories,17835,3,JazzCash
4989,ORD-14990,2026-01-05,Dell XPS 13,Laptop,296901,4,JazzCash
4994,ORD-14995,2026-01-25,Google Pixel 8,Mobile,214873,3,JazzCash
4997,ORD-14998,2025-06-06,Samsung S24,Mobile,234107,3,JazzCash

In [ ]:
#another way to query records
df[(df['Product'] == 'MacBook Air M2') & (df['Quantity'] >= 5) & (df['Payment_Method'].isin(['JazzCash','Cash']))]

,Order_ID,Date,Product,Category,Price,Quantity,Payment_Method
0,ORD-10001,2025-05-14,MacBook Air M2,Laptop,396538,5,JazzCash
72,ORD-10073,2025-09-26,MacBook Air M2,Laptop,338056,5,Cash
127,ORD-10128,2026-02-25,MacBook Air M2,Laptop,370489,5,JazzCash
149,ORD-10150,2025-12-13,MacBook Air M2,Laptop,397768,5,JazzCash
280,ORD-10281,2026-02-27,MacBook Air M2,Laptop,399204,5,Cash
315,ORD-10316,2025-10-20,MacBook Air M2,Laptop,334070,5,Cash
358,ORD-10359,2025-11-09,MacBook Air M2,Laptop,336898,5,JazzCash
376,ORD-10377,2025-10-12,MacBook Air M2,Laptop,371453,5,JazzCash
430,ORD-10431,2025-06-05,MacBook Air M2,Laptop,387541,5,Cash
438,ORD-10439,2025-05-05,MacBook Air M2,Laptop,369841,5,JazzCash
572,ORD-10573,2025-06-01,MacBook Air M2,Laptop,341964,5,JazzCash
601,ORD-10602,2025-06-23,MacBook Air M2,Laptop,308715,5,JazzCash
768,ORD-10769,2025-12-26,MacBook Air M2,Laptop,370064,5,JazzCash
818,ORD-10819,2026-01-17,MacBook Air M2,Laptop,389117,5,JazzCash
863,ORD-10864,2025-09-12,MacBook Air M2,Laptop,377882,5,Cash
957,ORD-10958,2025-06-08,MacBook Air M2,Laptop,310311,5,JazzCash
983,ORD-10984,2025-07-18,MacBook Air M2,Laptop,324445,5,Cash
1063,ORD-11064,2025-06-26,MacBook Air M2,Laptop,310620,5,Cash
1187,ORD-11188,2026-02-04,MacBook Air M2,Laptop,356512,5,JazzCash
1234,ORD-11235,2026-01-12,MacBook Air M2,Laptop,309725,5,Cash
1267,ORD-11268,2025-11-27,MacBook Air M2,Laptop,382480,5,Cash
1354,ORD-11355,2025-10-28,MacBook Air M2,Laptop,387780,5,JazzCash
1566,ORD-11567,2025-09-08,MacBook Air M2,Laptop,308302,5,Cash
1605,ORD-11606,2025-05-20,MacBook Air M2,Laptop,318759,5,Cash
1625,ORD-11626,2026-02-06,MacBook Air M2,Laptop,353342,5,Cash
1663,ORD-11664,2025-05-20,MacBook Air M2,Laptop,340481,5,JazzCash
2075,ORD-12076,2026-03-07,MacBook Air M2,Laptop,324949,5,JazzCash
2155,ORD-12156,2025-05-03,MacBook Air M2,Laptop,362130,5,JazzCash
2247,ORD-12248,2025-08-13,MacBook Air M2,Laptop,363731,5,JazzCash
2345,ORD-12346,2026-01-08,MacBook Air M2,Laptop,372506,5,JazzCash
2367,ORD-12368,2026-03-13,MacBook Air M2,Laptop,344078,5,Cash
2585,ORD-12586,2026-01-29,MacBook Air M2,Laptop,302671,5,Cash
2596,ORD-12597,2026-02-28,MacBook Air M2,Laptop,318117,5,Cash
2657,ORD-12658,2025-07-29,MacBook Air M2,Laptop,303109,5,JazzCash
2783,ORD-12784,2025-12-08,MacBook Air M2,Laptop,398699,5,JazzCash
2805,ORD-12806,2025-06-02,MacBook Air M2,Laptop,384329,5,Cash
2847,ORD-12848,2025-12-08,MacBook Air M2,Laptop,352160,5,JazzCash
2849,ORD-12850,2025-04-30,MacBook Air M2,Laptop,361499,5,Cash
2871,ORD-12872,2025-11-05,MacBook Air M2,Laptop,374468,5,Cash
2894,ORD-12895,2025-12-25,MacBook Air M2,Laptop,305484,5,Cash
2928,ORD-12929,2025-10-13,MacBook Air M2,Laptop,388193,5,JazzCash
3213,ORD-13214,2025-11-21,MacBook Air M2,Laptop,334405,5,JazzCash
3289,ORD-13290,2025-12-26,MacBook Air M2,Laptop,386921,5,JazzCash
3334,ORD-13335,2025-06-20,MacBook Air M2,Laptop,341130,5,JazzCash
3480,ORD-13481,2025-06-30,MacBook Air M2,Laptop,328850,5,Cash
3685,ORD-13686,2025-10-11,MacBook Air M2,Laptop,321397,5,Cash
3700,ORD-13701,2025-08-20,MacBook Air M2,Laptop,313464,5,Cash
3859,ORD-13860,2025-12-05,MacBook Air M2,Laptop,305496,5,JazzCash
3981,ORD-13982,2026-02-15,MacBook Air M2,Laptop,310409,5,JazzCash
4161,ORD-14162,2026-01-21,MacBook Air M2,Laptop,313672,5,JazzCash
4230,ORD-14231,2025-08-26,MacBook Air M2,Laptop,306782,5,Cash
4296,ORD-14297,2025-07-24,MacBook Air M2,Laptop,319785,5,Cash
4390,ORD-14391,2026-02-02,MacBook Air M2,Laptop,305781,5,Cash
4439,ORD-14440,2025-04-29,MacBook Air M2,Laptop,355006,5,Cash
4629,ORD-14630,2025-05-08,MacBook Air M2,Laptop,358677,5,Cash
4652,ORD-14653,2025-09-04,MacBook Air M2,Laptop,313486,5,JazzCash
4938,ORD-14939,2025-12-18,MacBook Air M2,Laptop,332320,5,Cash
4943,ORD-14944,2025-06-21,MacBook Air M2,Laptop,369282,5,JazzCash

In [ ]:
#filtering specific columns in result only (more like select statement)
df.filter(items=['Order_ID','Payment_Method'])

       Order_ID Payment_Method
0     ORD-10001       JazzCash
1     ORD-10002      EasyPaisa
2     ORD-10003       JazzCash
3     ORD-10004    Credit Card
4     ORD-10005    Credit Card
...         ...            ...
4995  ORD-14996           Cash
4996  ORD-14997      EasyPaisa
4997  ORD-14998       JazzCash
4998  ORD-14999      EasyPaisa
4999  ORD-15000           Cash

[5000 rows x 2 columns]

In [66]:
print(df.dropna())

       Order_ID        Date          Product     Category   Price  Quantity  \
0     ORD-10001  2025-05-14   MacBook Air M2       Laptop  396538         5
1     ORD-10002  2025-05-07  Sony WH-1000XM5  Accessories   94182         1
2     ORD-10003  2025-05-19        iPhone 15       Mobile  321269         4
3     ORD-10004  2026-01-16      Airpods Pro  Accessories   51859         5
4     ORD-10005  2025-07-02      Airpods Pro  Accessories   58606         2
...         ...         ...              ...          ...     ...       ...
4995  ORD-14996  2025-11-29        iPhone 15       Mobile  320392         4
4996  ORD-14997  2025-09-15      Airpods Pro  Accessories   54518         2
4997  ORD-14998  2025-06-06      Samsung S24       Mobile  234107         3
4998  ORD-14999  2025-06-25        iPhone 15       Mobile  303658         5
4999  ORD-15000  2026-03-02      Dell XPS 13       Laptop  362826         1

     Payment_Method
0          JazzCash
1         EasyPaisa
2          JazzCash
3       Credit Card
4       Credit Card
...             ...
4995           Cash
4996      EasyPaisa
4997       JazzCash
4998      EasyPaisa
4999           Cash

[5000 rows x 7 columns]